--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Players; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Players" (
    "ID" bigint NOT NULL,
    "LastName" text NOT NULL,
    "FirstName" text NOT NULL,
    "Gender" integer NOT NULL,
    "BirthDate" date NOT NULL,
    "TeamID" bigint NOT NULL,
    "Country" integer NOT NULL
);


ALTER TABLE public."Players" OWNER TO postgres;

--
-- Name: Players_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Players" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Players_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Teams" (
    "ID" bigint NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Teams" OWNER TO postgres;

--
-- Name: Teams_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Teams" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Teams_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Players; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Players" ("ID", "LastName", "FirstName", "Gender", "BirthDate", "TeamID", "Country") FROM stdin;
1	Doe	John	0	1990-01-01	1	1
2	Smith	Alice	1	1995-02-15	2	2
\.


--
-- Data for Name: Teams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Teams" ("ID", "Name") FROM stdin;
1	Test1
2	Test2
3	Test3
4	qqq
5	121
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240314082014_Init	7.0.17
20240314094926_Fix	7.0.17
\.


--
-- Name: Players_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Players_ID_seq"', 6, true);


--
-- Name: Teams_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Teams_ID_seq"', 5, true);


--
-- Name: Players PK_Players; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Players"
    ADD CONSTRAINT "PK_Players" PRIMARY KEY ("ID");


--
-- Name: Teams PK_Teams; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Teams"
    ADD CONSTRAINT "PK_Teams" PRIMARY KEY ("ID");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Players_TeamID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Players_TeamID" ON public."Players" USING btree ("TeamID");


--
-- Name: Players FK_Players_Teams_TeamID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Players"
    ADD CONSTRAINT "FK_Players_Teams_TeamID" FOREIGN KEY ("TeamID") REFERENCES public."Teams"("ID") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

